version: "3.1"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"

  # -------------------- flat-service --------------------

  consul-flat-service:
    image: consul:1.14.3
    ports:
      - "8500:8500"

  haproxy-flat-service:
    build: haproxy-flat
    depends_on:
      - flat-service-1
      - flat-service-2
      - consul-flat-service
    ports:
      - "1443:443"
      - "5555:5555"

  flat-service-1:
    build: flat-service
    depends_on:
      - postgres
      - consul-flat-service
    environment:
      SERVICE_PORT: 443
      SERVICE_NAME: flat-service-1
    ports:
      - "11443:443"
      - "14848:4848"

  flat-service-2:
    build: flat-service
    depends_on:
      - postgres
      - consul-flat-service
    environment:
      SERVICE_PORT: 443
      SERVICE_NAME: flat-service-2
    ports:
      - "12443:443"
      - "24848:4848"

  # -------------------- agency-service-web --------------------

  haproxy-agency-service-web:
    build: haproxy-agency-web
    depends_on:
      - agency-service-web-1
      - agency-service-web-2
    ports:
      - "2443:443"

  agency-service-web-1:
    build: agency-service-web
    depends_on:
      - haproxy-agency-service-ejb
    ports:
      - "21443:443"

  agency-service-web-2:
    build: agency-service-web
    depends_on:
      - haproxy-agency-service-ejb
    ports:
      - "22443:443"

  # -------------------- agency-service-ejb --------------------

  haproxy-agency-service-ejb:
    build: haproxy-agency-ejb
    depends_on:
      - agency-service-ejb-1
      - agency-service-ejb-2
    ports:
      - "28080:8080"
      - "28404:8404"

  agency-service-ejb-1:
    build: agency-service-ejb
    depends_on:
      - haproxy-flat-service

  agency-service-ejb-2:
    build: agency-service-ejb
    depends_on:
      - haproxy-flat-service

volumes:
  pg-data:
    external: true
